const fs = require('fs');
const sharp = require('sharp');
let heicConvert;
try { heicConvert = require('heic-convert'); } catch { heicConvert = null; }

function parseDate(value){ if(!value) return null; const m=String(value).match(/(\d{1,2})[\.\/\-](\d{1,2})[\.\/\-](\d{2,4})/); if(!m) return null; const y=m[3].length===2?'20'+m[3]:m[3]; return `${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`; }
function parseAmount(raw){ if(!raw) return null; const s=String(raw).replace(/\s/g,'').replace(/\./g,'').replace(',', '.'); const n=Number(s); return Number.isFinite(n)?n:null; }
function bestAmount(text){ const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean); const keyLine=lines.find(l=>/(TOPLAM|GENEL\s*TOPLAM|TUTAR|KREDİ|NAKİT)/i.test(l)&&/(\d+[\.,]\d{2})/.test(l)); const source=keyLine||text; const nums=[...source.matchAll(/\d{1,3}(?:\.\d{3})*[\.,]\d{2}|\d+[\.,]\d{2}/g)].map(m=>parseAmount(m[0])).filter(Boolean); return nums.length?Math.max(...nums):null; }
function parseReceiptText(text){ const clean=text||''; const lines=clean.split(/\r?\n/).map(x=>x.trim()).filter(Boolean); const dateMatch=clean.match(/\d{1,2}[\.\/\-]\d{1,2}[\.\/\-]\d{2,4}/); const vatLine=lines.find(l=>/KDV/i.test(l)&&/(\d+[\.,]\d{2})/.test(l)); const taxLine=lines.find(l=>/(MATRAH|ARA\s*TOPLAM|NET)/i.test(l)&&/(\d+[\.,]\d{2})/.test(l)); const receiptLine=lines.find(l=>/(FİŞ|FIS|F NO|FİŞ NO|FIS NO)/i.test(l)); const docLine=lines.find(l=>/(BELGE|FATURA|EVRAK)/i.test(l)); return { companyName: lines[0] || '', documentDate: parseDate(dateMatch?.[0]), expenseDate: parseDate(dateMatch?.[0]), documentNo: docLine?.match(/[A-Z0-9\-]{4,}/i)?.[0] || '', receiptNo: receiptLine?.match(/[A-Z0-9\-]{3,}/i)?.[0] || '', taxBase: parseAmount(taxLine?.match(/\d{1,3}(?:\.\d{3})*[\.,]\d{2}|\d+[\.,]\d{2}/)?.[0]), vatAmount: parseAmount(vatLine?.match(/\d{1,3}(?:\.\d{3})*[\.,]\d{2}|\d+[\.,]\d{2}/)?.[0]), totalAmount: bestAmount(clean), rawText: clean }; }
async function normalizeImage(file){ let input=fs.readFileSync(file.path); const lower=(file.originalname||'').toLowerCase(); if((lower.endsWith('.heic')||lower.endsWith('.heif')) && heicConvert){ input=await heicConvert({buffer:input,format:'JPEG',quality:0.9}); }
 return sharp(input).rotate().resize({width:1800,height:1800,fit:'inside',withoutEnlargement:true}).jpeg({quality:88}).toBuffer(); }
async function googleVision(buffer){ const key=process.env.GOOGLE_VISION_API_KEY; if(!key) throw new Error('GOOGLE_VISION_API_KEY eksik'); const body={requests:[{image:{content:buffer.toString('base64')},features:[{type:'DOCUMENT_TEXT_DETECTION'}]}]}; const r=await fetch(`https://vision.googleapis.com/v1/images:annotate?key=${key}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const json=await r.json(); if(!r.ok || json.error) throw new Error(json.error?.message || 'Google Vision OCR hatası'); const text=json.responses?.[0]?.fullTextAnnotation?.text || json.responses?.[0]?.textAnnotations?.[0]?.description || ''; if(!text.trim()) throw new Error('OCR metni boş döndü'); return {text, provider:'google', textLength:text.length}; }
async function runOcr(file){ const buffer=await normalizeImage(file); const result=await googleVision(buffer); const parsed=parseReceiptText(result.text); return {...parsed, debug:{provider:result.provider,textLength:result.textLength,mimeType:file.mimetype,fileSize:file.size}}; }
module.exports={runOcr,parseReceiptText};
