require('dotenv').config();
const express=require('express'); const session=require('express-session'); const path=require('path'); const pgSession=require('connect-pg-simple')(session); const {Pool}=require('pg'); const prisma=require('./lib/prisma'); const {requireAuth}=require('./middleware/auth'); const {layout,money}=require('./views/layout');
const app=express(); const PORT=process.env.PORT||3000;
app.use(express.urlencoded({extended:true})); app.use(express.json()); app.use('/public',express.static(path.join(__dirname,'..','public'))); app.use('/uploads',express.static(path.join(process.cwd(),process.env.UPLOAD_DIR||'uploads')));
const sess={secret:process.env.SESSION_SECRET||'dev-secret-change-me',resave:false,saveUninitialized:false,cookie:{maxAge:1000*60*60*24*7}}; if(process.env.DATABASE_URL){ sess.store=new pgSession({pool:new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('railway')?{rejectUnauthorized:false}:undefined}),createTableIfMissing:true}); }
app.use(session(sess));
app.get('/healthz',(req,res)=>res.status(200).send('ok'));
app.get('/api/version',(req,res)=>res.json({name:'moduler-masraf',version:'19.1.0',ok:true}));
app.use(require('./routes/auth')); app.use(require('./routes/ocr')); app.use('/expenses',require('./routes/expenses')); app.use('/approvals',require('./routes/approvals')); app.use('/finance',require('./routes/finance')); app.use('/admin',require('./routes/admin'));
app.get('/',requireAuth,async(req,res)=>{ const where=req.session.user.role==='PERSONEL'?{ownerId:req.session.user.id}:{}; const [count,total,pending,paid]=await Promise.all([prisma.expense.count({where}),prisma.expense.aggregate({where,_sum:{totalAmount:true}}),prisma.expense.count({where:{...where,status:{in:['PENDING_APPROVAL','PENDING_ACCOUNTING','PENDING_FINANCE','PAYMENT_WAITING']}}}),prisma.expense.count({where:{...where,status:'PAID'}})]); res.send(layout(req,'Ana Sayfa',`<div class="card"><h1>Merhaba ${req.session.user.name}</h1><p class="muted">Mobil uyumlu OCR + Risk + Onay + Finans masraf sistemi.</p><a class="buttonlink" href="/expenses/new">+ Masraf Ekle</a></div><div class="grid"><div class="card"><h2>Masraf Adedi</h2><p class="big">${count}</p></div><div class="card"><h2>Toplam</h2><p class="big">${money(total._sum.totalAmount)} TL</p></div><div class="card"><h2>Bekleyen</h2><p class="big">${pending}</p></div><div class="card"><h2>Ödenen</h2><p class="big">${paid}</p></div></div>`)); });
app.use((err,req,res,next)=>{ console.error(err); res.status(500).send(layout(req,'Hata',`<div class="card"><h1>Sunucu Hatası</h1><pre>${String(err.stack||err.message)}</pre></div>`)); });
app.listen(PORT,()=>console.log(`Modüler Masraf v19 çalışıyor: ${PORT}`));
